version: "3"

services:
  app:
    build: requirements/app
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - /Users/sanghyol/ft_transcendence/srcs/requirements/app:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres